function skillsMember() {
  const skills = [
    'HTML',
    'CSS',
    'JavaScript',
    'ReactJS',
    'NodeJS',
    'Express',
    'MongoDB',
    'Python',
    'Django',
    'Flask',
    'Machine Learning',
    'Data Science',
    'Artificial Intelligence',
    'Blockchain',
    'Solidity',
    'Web3',
    'Ethereum',
    'Bitcoin',
    'Rust',
    'C++',
    'Java',
    'C#',
    'Unity',
    'Unreal Engine',
    'Blender',
    'Maya',
    'Photoshop',
    'Illustrator',
    'Premiere Pro',
    'After Effects',
    '3ds Max',
    'ZBrush',
    'Substance Painter',
    'Substance Designer',
    'Figma',
    'Sketch',
    'InVision',
    'Adobe XD',
    'Unity',
    'Unreal Engine',
    'AR',
    'VR',
    'UI/UX Design',
    'Product Design',
    'Game Design',
    'Game Development',
    'Mobile Development',
    'Web Development',
    'Backend Development',
    'Frontend Development',
    'Fullstack Development',
    'DevOps',
    'Cloud Computing',
    'Cybersecurity',
    'Network Security',
    'Penetration Testing',
    'Ethical Hacking',
    'Bug Bounty',
    'Reverse Engineering',
    'Forensics',
    'Incident Response',
    'Security Operations',
    'Security Engineering',
    'Security Architecture',
    'Security Analysis',
    'Security Auditing',
    'Security Compliance',
    'Security Governance',
    'Security Policy',
    'Security Risk Management',
    'Security Strategy',
    'Security Program Management',
    'Security Awareness',
    'Security Education',
    'Security Training',
    'Security Culture',
    'Security Leadership',
    'Security Management',
    'Security Administration',
    'Security Operations',
    'Security Engineering',
    'Security Architecture',
    'Security Analysis',
    'Security Auditing',
    'Security Compliance',
    'Security Governance',
    'Security Policy',
    'Security Risk Management',
    'Security Strategy',
    'Security Program Management',
    'Security Awareness',
    'Security Education',
    'Security Training',
    'Security Culture',
    'Security Leadership',
    'Security Management',
    ];
  
    return skills;
  }